#spring.main.web-application-type: none
server:
  port: -1
# Additional server ports specified with Armeria configuration.
armeria:
  ports:
    - port: 8080
      protocols:
        - http
  internal-services:
    include: docs, health, metrics, actuator
  health-check-path: /internal/healthcheck
  enable-metrics: true
